### ISSUE TITLE
flaky `make test`

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#439]
[example](https://app.circleci.com/pipelines/github/babylonchain/finality-provider/1589/workflows/9e581924-d3e1-404a-89a8-83cd29a16658/jobs/3657/parallel-runs/0/steps/0-115)

![image](https://github.com/babylonchain/finality-provider/assets/111917526/64c81685-0aee-4cb5-9b0f-5d75b3895892)

this happens a bit too frequent cc @SebastianElvis

**Comment by SebastianElvis** [comment]
i guess it's simply that we have too many e2e tests so that it sometimes time out? https://app.circleci.com/pipelines/github/babylonchain/finality-provider/1589/workflows/9e581924-d3e1-404a-89a8-83cd29a16658/jobs/3657/parallel-runs/0/steps/0-115?invite=true#step-115-2974_33

If yes, how about we break down the CI pipeline a bit, e.g., 1 workflow for unit tests, 1 workflow for Babylon e2e, 1 workflow for wasm e2e, and 1 workflow for OP e2e?

**Comment by bap2pecs** [comment]
@SebastianElvis this is before the `make test-e2e` step. so I don't think the timeout is caused by e2e. if you see this one, you can see normal `make test` only takes 1 minute but this one takes 10 minutes so it timed out

<img width="1681" alt="image" src="https://github.com/babylonchain/finality-provider/assets/111917526/ac93f715-2c03-4301-b9f5-1d9b56ff91c8">

so I think we need to investigate into the unit test to understand why it failed sometimes. maybe it's related to the fuzzing tests but I am not sure

> 1 workflow for Babylon e2e, 1 workflow for wasm e2e, and 1 workflow for OP e2e

but this is a good idea. we can do it

**Comment by SebastianElvis** [comment]
Hmm I think you are right.

Digging into the error stack and I see

```
goroutine 222 [chan receive, 9 minutes]:
testing.(*F).Fuzz.func1({0x3c05ca0?, 0xc0017ec5a0}, {{0x0, 0x0}, {0xc000e0b7d8, 0x6}, {0x0, 0x0, 0x0}, {0xc000a42b10, ...}, ...})
        /usr/local/go/src/testing/fuzz.go:337 +0x5aa
testing.(*F).Fuzz(0xc0017ec5a0, {0x2d51ee0, 0x367be20})
        /usr/local/go/src/testing/fuzz.go:402 +0xa37
github.com/babylonchain/finality-provider/finality-provider/service_test.FuzzChainPoller_SkipHeight(0x4803e0?)
        /home/circleci/project/finality-provider/service/chain_poller_test.go:73 +0x35
testing.fRunner(0xc0017ec5a0, 0x367bcf8)
        /usr/local/go/src/testing/fuzz.go:722 +0xbe
created by testing.runFuzzTests in goroutine 1
        /usr/local/go/src/testing/fuzz.go:527 +0x84b
```

which is the test case `FuzzChainPoller_SkipHeight`. Does that mean sometimes this test case runs indefinitely?

**Comment by bap2pecs** [comment]
> Does that mean sometimes this test case runs indefinitely

maybe yes. i remember seeing this "SkipHeight" method failing sometimes

**Comment by bap2pecs** [comment]
the `FuzzChainPoller_SkipHeight ` failure happened again in #452

**Comment by bap2pecs** [comment]
I found another flaky task https://github.com/babylonchain/finality-provider/pull/451#issuecomment-2200177000

not sure why those flaky tasks become more frequent lately cc @gitferry @maurolacy @gusin13 do you guys also feel this way?

**Comment by bap2pecs** [comment]
```
=== RUN   TestBlockBabylonFinalized
    babylon_node_handler.go:148: babylon log file: /var/folders/9_/q4wsdnh14_s60_74cd2rbztm0000gp/T/zBabylonTest4068386431/babylon.log
    op_test_manager.go:84: Fp home dir: /var/folders/9_/q4wsdnh14_s60_74cd2rbztm0000gp/T/fpe2etest1247240042/fp-home
    setup.go:490: Generating L2 genesis l2_allocs_mode delta
    op_test_manager.go:110: Register consumer op-stack-l2-901 to Babylon
    op_test_manager.go:152: Deployed op finality contract address: bbn14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sw76fy2
    op_test_manager.go:160: 
        	Error Trace:	/Users/zidong/Documents/Projects/babylon-finality-provider/itest/opstackl2/op_test_manager.go:160
        	            				/Users/zidong/Documents/Projects/babylon-finality-provider/itest/opstackl2/op_e2e_test.go:109
        	Error:      	Received unexpected error:
        	            	the EOTS manager server is not responding: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:12582: connect: connection refused"
        	Test:       	TestBlockBabylonFinalized
--- FAIL: TestBlockBabylonFinalized (23.11s)
```

saw this again. probably due to EOTS was not ready yet?

**Comment by bap2pecs** [comment]
another flaky test in `test_e2e_babylon` job

https://github.com/babylonchain/finality-provider/pull/466#issuecomment-2207362361

```
=== RUN   TestMultipleFinalityProviders
    babylon_node_handler.go:148: babylon log file: /tmp/zBabylonTest1947099691/babylon.log
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
    babylon_test_manager.go:113: Babylon node is started
    babylon_test_manager.go:169: The test manager is running with 3 finality-provider(s)
fatal error: concurrent map writes
fatal error: concurrent map writes
```

**Comment by bap2pecs** [comment]
another flaky test when we enable fast sync in our e2e test `TestOpSubmitFinalitySignature`

```
2024-07-03T18:13:42.481-0400	INFO	service/fp_instance.go:337	successfully committed public randomness to the consumer chain	{"consumer_id": "op-stack-l2-901", "pk": "7f740f3eaeba7220cf0536ad711ab6949f9d6d75c6242789824d47c2ae1ae118", "tx_hash": "9E73C2029927120D285DBBFE6327E65A78FB5FF1FA2DFB2CE55274718E783FFD"}
2024-07-03T18:13:42.515-0400	INFO	cosmos/log.go:131	Successful transaction	{"chain_id": "chain-test", "gas_used": 1240653, "fees": "3665ubbn", "fee_payer": "l\ufffd\ufffd}\u0019\ufffd\u000bR\ufffd\ufffd+k{\ufffd\ufffd?\ufffd,f\ufffd", "height": 8, "msg_types": ["/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract", "/cosmwasm.wasm.v1.MsgExecuteContract"], "tx_hash": "672C886AD9ECEB62C1496024F776ADC46B42767B84F0C0936ADEE097BA5787F4"}
2024-07-03T18:13:42.535-0400	DEBUG	service/fastsync.go:91	the finality-provider is catching up by sending finality signatures in a batch	{"pk": "7f740f3eaeba7220cf0536ad711ab6949f9d6d75c6242789824d47c2ae1ae118", "start_height": 2, "synced_height": 11}
unexpected fault address 0x152b50b1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x152b50b1e pc=0x100efc2b4]

goroutine 619708 gp=0x140031d7dc0 m=4 mp=0x14000100008 [running]:
runtime.throw({0x103de88a5?, 0xa0?})
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/runtime/panic.go:1023 +0x40 fp=0x14008879360 sp=0x14008879330 pc=0x10098cc10
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/runtime/signal_unix.go:895 +0x22c fp=0x140088793c0 sp=0x14008879360 pc=0x1009a7f5c
github.com/cometbft/cometbft/proto/tendermint/crypto.(*Proof).Unmarshal(0x14008879608, {0x152b50b1e, 0xf2, 0xf2})
	/Users/zidong/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/proto/tendermint/crypto/proof.pb.go:698 +0x184 fp=0x140088794a0 sp=0x140088793d0 pc=0x100efc2b4
github.com/babylonchain/finality-provider/clientcontroller/opstackl2.(*OPStackL2ConsumerController).SubmitBatchFinalitySigs(0x140073e0ea0, 0x140077f3f40, {0x140067cb590, 0xa, 0x14003c54470?}, {0x14004e355e0, 0xa, 0x103248870?}, {0x140052c4d80, 0xa, ...}, ...)
	/Users/zidong/Documents/Projects/babylon-finality-provider/clientcontroller/opstackl2/consumer.go:194 +0x188 fp=0x140088796f0 sp=0x140088794a0 pc=0x1032390c8
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).SubmitBatchFinalitySignatures(0x14007093d40, {0x140067cb590, 0xa, 0xa})
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fp_instance.go:856 +0x2c8 fp=0x14008879800 sp=0x140088796f0 pc=0x10324e598
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).FastSync(0x14007093d40, 0x103eb3d0d?, 0x1a)
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fastsync.go:83 +0x260 fp=0x140088799f0 sp=0x14008879800 pc=0x1032484c0
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).tryFastSync(0x14007093d40, 0x1a)
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fp_instance.go:429 +0x11c fp=0x14008879b00 sp=0x140088799f0 pc=0x10324b7bc
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).finalitySigSubmissionLoop(0x14007093d40)
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fp_instance.go:246 +0xe0 fp=0x14008879fb0 sp=0x14008879b00 pc=0x103249ae0
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).Start.gowrap1()
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fp_instance.go:133 +0x28 fp=0x14008879fd0 sp=0x14008879fb0 pc=0x103249618
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.22.4/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14008879fd0 sp=0x14008879fd0 pc=0x1009cb474
created by github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).Start in goroutine 4246
	/Users/zidong/Documents/Projects/babylon-finality-provider/finality-provider/service/fp_instance.go:133 +0x580

```

**Comment by bap2pecs** [comment]
EOTS manager related flaky failure. likely there is some race condition

```
    setup.go:490: Generating L2 genesis l2_allocs_mode delta
2024-07-04T20:43:51.039-0400	INFO	cosmos/log.go:131	Successful transaction	{"chain_id": "chain-test", "gas_used": 71372, "fees": "2086ubbn", "fee_payer": "Iۙ\u0001ڌYP\"\ufffd\u001e\ufffd\ufffdFC\ufffd\ufffdS<-", "height": 4, "msg_types": ["/babylon.btcstkconsumer.v1.MsgRegisterConsumer"], "tx_hash": "A1ADFA98B2566478825BB6E2C29D8B2BD315BB2328A9A000A21431018C561B15"}
    op_test_manager.go:150: Register consumer op-stack-l2-901 to Babylon
    op_test_manager.go:170: 
        	Error Trace:	/Users/zidong/Documents/Projects/babylon-finality-provider/itest/opstackl2/op_test_manager.go:170
        	            				/Users/zidong/Documents/Projects/babylon-finality-provider/itest/opstackl2/op_e2e_test.go:119
        	Error:      	Received unexpected error:
        	            	the EOTS manager server is not responding: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:12582: connect: connection refused"
        	Test:       	TestOpMultipleFinalityProviders
--- FAIL: TestOpMultipleFinalityProviders (21.87s)
```

**Comment by lesterli** [comment]
After changing the value of `defaultPollingInterval` to **2s**, the e2e test case `TestDoubleSigning` was failed. 
```
babylon_test_manager.go:254: the block is finalized at 8
    babylon_e2e_test.go:99: the equivocation attack is successful
    babylon_test_manager.go:260: 
                Error Trace:    /Users/lyy/babylon/finality-provider/itest/babylon/babylon_test_manager.go:260
                                                        /Users/lyy/babylon/finality-provider/itest/babylon/babylon_e2e_test.go:101
                Error:          Condition never satisfied
                Test:           TestDoubleSigning
FAIL    github.com/babylonchain/finality-provider/itest/babylon 597.114s
```

**Comment by bap2pecs** [comment]
docker image build sometimes can also fail:

![image](https://github.com/user-attachments/assets/305f4893-a4db-40c0-89aa-7065bbdbd8bf)

**Comment by bap2pecs** [comment]
quite interesting that I found a flaky test in https://github.com/babylonchain/finality-provider/pull/526

https://app.circleci.com/pipelines/github/babylonchain/finality-provider/1996/workflows/f0949f6d-2f37-4cbd-be03-bb0773cea599/jobs/5831 failed due to a flaky data race

<details><summary>data race</summary>

```
=== RUN   TestFinalityStuckAndRecover
    babylon_node_handler.go:153: babylon log file: /tmp/zBabylonTest2527062729/babylon.log
Starting babylond with command:  /home/circleci/.go_workspace/bin/babylond start --home=/tmp/zBabylonTest2527062729/node0/babylond --log_level=trace --trace
2024-07-20T23:38:00.999Z	INFO	cosmos/log.go:131	Successful transaction	{"chain_id": "chain-test", "gas_used": 2690989, "fees": "8016ubbn", "fee_payer": "\ufffd\ufffd\ufffdЬ\ufffd@\u0010\ufffd\"\u0005\ufffd\u000bTN$\ufffd\ufffd-\ufffd", "height": 2, "msg_types": ["/cosmwasm.wasm.v1.MsgStoreCode"], "tx_hash": "153B06308B4F1E2A64B4193BCA2C8FE5138C162750C9A9544D236577C1E2F895"}
2024-07-20T23:38:05.911Z	INFO	cosmos/log.go:131	Successful transaction	{"chain_id": "chain-test", "gas_used": 170224, "fees": "454ubbn", "fee_payer": "\ufffd\ufffd\ufffdЬ\ufffd@\u0010\ufffd\"\u0005\ufffd\u000bTN$\ufffd\ufffd-\ufffd", "height": 3, "msg_types": ["/cosmwasm.wasm.v1.MsgInstantiateContract"], "tx_hash": "05CF67BC2991E7A36028F5906B0AD94CCA3FE6FB969C6E593A9F541DD513391F"}
    op_test_manager.go:372: [23:38:05.913] op-finality-gadget contract address: bbn14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sw76fy2
    setup.go:490: Generating L2 genesis l2_allocs_mode delta
==================
WARNING: DATA RACE
Write at 0x00c0080da060 by goroutine 1152692:
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).initL2()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-node/node/node.go:404 +0x1529
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).init()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-node/node/node.go:130 +0x3cd
  github.com/ethereum-optimism/optimism/op-node/node.New()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-node/node/node.go:107 +0x3c4
  github.com/ethereum-optimism/optimism/op-e2e.SystemConfig.Start()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-e2e/setup.go:737 +0x3dc8
  github.com/babylonchain/finality-provider/itest/opstackl2.startExtSystemsAndCreateConsumerCfg()
      /home/circleci/project/itest/opstackl2/op_test_manager.go:618 +0x7cd
  github.com/babylonchain/finality-provider/itest/opstackl2.StartOpL2ConsumerManager()
      /home/circleci/project/itest/opstackl2/op_test_manager.go:81 +0x129
  github.com/babylonchain/finality-provider/itest/opstackl2.TestFinalityStuckAndRecover()
      /home/circleci/project/itest/opstackl2/op_e2e_test.go:123 +0x44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c0080da060 by goroutine 1153399:
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).OnNewL1Head()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-node/node/node.go:526 +0xf3
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).OnNewL1Head-fm()
      <autogenerated>:1 +0x75
  github.com/ethereum-optimism/optimism/op-service/eth.WatchHeadChanges.func1()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-service/eth/heads.go:46 +0x361
  github.com/ethereum/go-ethereum/event.NewSubscription.func1()
      /home/circleci/.go_workspace/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.1-rc.5/event/subscription.go:53 +0xd4

Goroutine 1152692 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:51 +0x2bd

Goroutine 1153399 (running) created at:
  github.com/ethereum/go-ethereum/event.NewSubscription()
      /home/circleci/.go_workspace/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.1-rc.5/event/subscription.go:51 +0x1bc
  github.com/ethereum-optimism/optimism/op-service/eth.WatchHeadChanges()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-service/eth/heads.go:28 +0x177
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).initL1.func1()
      /home/circleci/.go_workspace/pkg/mod/github.com/babylonchain/optimism@v1.7.5-0.20240717115935-8fad1ec9aa03/op-node/node/node.go:191 +0x1f4
  github.com/ethereum/go-ethereum/event.(*resubscribeSub).subscribe.func1()
      /home/circleci/.go_workspace/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.1-rc.5/event/subscription.go:175 +0xb3
==================
    op_test_manager.go:200: [23:38:11.107] Fp home dir: /tmp/fpe2etest354798435/fp-home-0
    op_test_manager.go:258: Error checking balance: no balances found for address bbn1s6nf278lsn4eaevjzmgxmxhcm7sjv9mk5h7ada
    op_test_manager.go:258: Error checking balance: no balances found for address bbn1s6nf278lsn4eaevjzmgxmxhcm7sjv9mk5h7ada
    op_test_manager.go:264: [23:38:17.605] Sent 1000000ubbn to bbn1s6nf278lsn4eaevjzmgxmxhcm7sjv9mk5h7ada
    op_test_manager.go:200: [23:38:17.605] Fp home dir: /tmp/fpe2etest354798435/fp-home-1
    op_test_manager.go:258: Error checking balance: no balances found for address bbn1rcc8peydcuedta6xkhsam9vltryss600l5qzml
    op_test_manager.go:264: [23:38:22.156] Sent 1000000ubbn to bbn1rcc8peydcuedta6xkhsam9vltryss600l5qzml
```

</details>

**Comment by gitferry** [comment]
seems we can close it as fast sync is removed?
